### PR TITLE
for a twitter:label/data meta tags, we must use a 'value' attr

### PR DESCRIPTION
**Pull request by amensouissi**

### CODE REVIEW

**Comment by jvanasco** [comment]
do you have a reference for where/when these appear?  i'd like to build them into tests and ensure other tags aren't missing.

**Comment by amensouissi** [comment]
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by jvanasco** [comment]
Ah, I wouldn't worry about those.  They're from the "Product Card" which Twitter deprecated in 2015.  It wasn't adopted widely, and isn't supported anymore.

I'll add support for this anyways - since a lot of people make bad implementations and use content instead of value and vice-versa.

**Comment by amensouissi** [comment]
thank you!

**Comment by jvanasco** [comment]
Closing this for Issue #14 and a PR to extend your commits which i'm working on...

**Comment by jvanasco** [comment]
a reworked version is available via github master and pypi `0.9.20`

the two differences from your PR:

* if the computed value is `None`, it will omit the tag from results. this is for backwards compatibility - tossing in a `None` value could break some installs as this only ever returned/stored a string before.

* if you pass in `support_malformed=True` to the constructor or `parse()`, it will enable a value>content or content>value failover on twitter tags.

**Pull request closed without merging**
